/* Automatically generated by mkexports.lua */
#include <libextl/extl.h>
#include <libextl/private.h>

EXTL_DEFCLASS(WMgmtMode);
EXTL_DEFCLASS(WRegion);
static bool l2chnd_o_o__WRegion(Obj* (*fn)(), ExtlL2Param *in, ExtlL2Param *out)
{
    if(!EXTL_CHKO1(in, 0, WRegion)) return FALSE;
    out[0].o=fn(in[0].o);
    return TRUE;
}
static bool l2chnd_o_o__WMgmtMode(Obj* (*fn)(), ExtlL2Param *in, ExtlL2Param *out)
{
    if(!EXTL_CHKO1(in, 0, WMgmtMode)) return FALSE;
    out[0].o=fn(in[0].o);
    return TRUE;
}
static bool l2chnd_v_o__WMgmtMode(void (*fn)(), ExtlL2Param *in, ExtlL2Param *out)
{
    if(!EXTL_CHKO1(in, 0, WMgmtMode)) return FALSE;
    fn(in[0].o);
    return TRUE;
}
static bool l2chnd_v_oo__WMgmtMode_WRegion(void (*fn)(), ExtlL2Param *in, ExtlL2Param *out)
{
    if(!EXTL_CHKO1(in, 0, WMgmtMode)) return FALSE;
    if(!EXTL_CHKO(in, 1, WRegion)) return FALSE;
    fn(in[0].o, in[1].o);
    return TRUE;
}

extern void mod_mgmtmode_begin();


static ExtlExportedFnSpec mod_mgmtmode_exports[] = {
    {"begin", mod_mgmtmode_begin, "o", "o", (ExtlL2CallHandler*)l2chnd_o_o__WRegion, FALSE, FALSE, FALSE},
    {NULL, NULL, NULL, NULL, NULL, FALSE, FALSE, FALSE}
};

extern void mgmtmode_selected();
extern void mgmtmode_finish();
extern void mgmtmode_select();


static ExtlExportedFnSpec WMgmtMode_exports[] = {
    {"selected", mgmtmode_selected, "o", "o", (ExtlL2CallHandler*)l2chnd_o_o__WMgmtMode, TRUE, FALSE, FALSE},
    {"finish", mgmtmode_finish, "o", NULL, (ExtlL2CallHandler*)l2chnd_v_o__WMgmtMode, FALSE, FALSE, FALSE},
    {"select", mgmtmode_select, "oo", NULL, (ExtlL2CallHandler*)l2chnd_v_oo__WMgmtMode_WRegion, FALSE, FALSE, FALSE},
    {NULL, NULL, NULL, NULL, NULL, FALSE, FALSE, FALSE}
};

#define WRegion_exports NULL
bool mod_mgmtmode_register_exports()
{
    if(!extl_register_module("mod_mgmtmode", mod_mgmtmode_exports)) return FALSE;
    if(!extl_register_class("WMgmtMode", WMgmtMode_exports, "Obj")) return FALSE;
    return TRUE;
}

void mod_mgmtmode_unregister_exports()
{
    extl_unregister_module("mod_mgmtmode", mod_mgmtmode_exports);
    extl_unregister_class("WMgmtMode", WMgmtMode_exports);
}

