/* Automatically generated by mkexports.lua */
#ifndef MOD_MGMTMODE_EXTL_EXPORTS_H
#define MOD_MGMTMODE_EXTL_EXPORTS_H

#include <libextl/extl.h>

extern bool mod_mgmtmode_register_exports();
extern void mod_mgmtmode_unregister_exports();

#endif /* MOD_MGMTMODE_EXTL_EXPORTS_H */

