-- This file has been generated by ../../notion/notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "default",
                },
                ["name"] = "WGroupWS",
                ["level"] = 0,
                ["geom"] = {
                    ["y"] = 0,
                    ["h"] = 1024,
                    ["w"] = 1280,
                    ["x"] = 0,
                },
                ["switchto"] = true,
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,
                                    ["managed"] = {
                                    },
                                    ["name"] = "Notion WFrame<1>",
                                },
                            },
                            ["dir"] = "horizontal",
                            ["tl"] = {
                                ["type"] = "WSplitSplit",
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["dir"] = "vertical",
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["mode"] = 1,
                                        ["managed"] = {
                                        },
                                        ["name"] = "Notion WFrame",
                                    },
                                },
                                ["tls"] = 1009,
                                ["brs"] = 15,
                            },
                            ["tls"] = 640,
                            ["brs"] = 640,
                        },
                        ["name"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["y"] = 0,
                            ["h"] = 1024,
                            ["w"] = 1280,
                            ["x"] = 0,
                        },
                    },
                },
            },
            [2] = {
                ["geom"] = {
                    ["y"] = 0,
                    ["h"] = 1024,
                    ["w"] = 1280,
                    ["x"] = 0,
                },
                ["hidden"] = true,
                ["initial_outputs"] = {
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WFrame",
                        ["sizepolicy"] = "free_glue",
                        ["bottom"] = true,
                        ["name"] = "*scratchpad*",
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["geom"] = {
                            ["y"] = 272,
                            ["h"] = 480,
                            ["w"] = 640,
                            ["x"] = 320,
                        },
                        ["managed"] = {
                        },
                    },
                },
                ["level"] = 1,
                ["type"] = "WGroupWS",
                ["pseudomodal"] = true,
                ["unnumbered"] = true,
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*",
            },
        },
        ["name"] = "WScreen",
    },
}

