.TH "INSTALL-NOTION-CFG"
.SH NAME
install-notion-cfg - Install script for Notion configuration
.SH SYNOPSIS
.B install-notion-cfg
.I "[--remove]"
.I "config-basename"
.SH DESCRIPTION

Script to add and remove Notion modules from the configuration.

.SH "OPTIONS"
.TP
.B \-\-remove
Remove the module from the configuration
.TP
.B config-basename
The name of the module to add or remove, without the '.lua' file extension

.SH SEE ALSO
\fInotion(1)\fP

.SH AUTHOR
Notion was written by the Notion team.
